### ISSUE TITLE
Error: ENOENT: no such file or directory, unlink './encoding/finished/St0rm#0001.txt'

### ISSUE THREAD

**Issue by TheFinality** [rutkuli/Discord-javascript-obfuscator#4]
Error: ENOENT: no such file or directory, unlink './encoding/finished/St0rm#0001.txt' wont work when i put a file, rip

**Comment by rutkuli** [comment]
Hey, please try sending the command with file you want to encrypt. Also that specific directory is for the finished obfuscated files.

**Comment by rutkuli** [comment]
Hey, github made an little mistake while uploading empty directories, so you need to create those directories encoding
encoding/finished.

**Comment by rutkuli** [comment]
And if you are having broplems after creating those directories, you can unzip obfuscator.rar from the github repository.

**Comment by TheFinality** [comment]
i fixed it, i just made a tiny code that made the file so anyone can. use it :D

**Comment by rutkuli** [comment]
I think you just didn't know how to use it, because many people have tried it and it worked just fine without modifying anything.

**Comment by rutkuli** [comment]
download(message.attachments.first().url, `./encoding/`, {
                            'filename': `${message.author.tag}.txt` /*Forces the file to be saved as txt file*/
                        });
Next time read the code thoroughly before making issues.
